# Generated by Django 4.2.4 on 2023-09-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_Aprendiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aprendiz',
            name='numero_documento',
            field=models.CharField(default=0, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='año_nacimiento',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='numero_ficha',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte')], max_length=2),
        ),
    ]
