# Generated by Django 4.2.4 on 2023-09-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_Aprendiz', '0003_alter_aprendiz_numero_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprendiz',
            name='año_nacimiento',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='numero_documento',
            field=models.CharField(max_length=20),
        ),
    ]
